language: node_js
node_js: node
before_script:
  - git config --global user.name "John Doe"
  - git config --global user.email johndoe@example.org
after_script: node_modules/.bin/nyc report --reporter=text-lcov | npx coveralls
env:
  global:
    secure: AyV0RreeMm/z1BIjjlTw3I7f/sbNblMfEoTabC41FTDK3i7GvJYsgqS9N38ACNKmB7i89mUr+GzKsXY3FoD7k6DGlSbjM9jYi6O2nEwa3/Q3RUVAXFJLQhr/IxlAsAv0Cp4jY6g7cA6qbVv0vbTUfnnC+0xoFl61EeEE3uv8uzE=
